/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp.views;

import bankapp.accounts.Bank;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DepositView extends javax.swing.JFrame {

    /**
     * Creates new form DepositMenu
     */
 
    private Bank bank;
    DepositView(Bank bank) {
         initComponents();
         setLocationRelativeTo(null);
         this.bank = bank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accountNoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dipositAmountField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        DepositButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 2, 4, 3));

        jLabel1.setText(" Account No :");
        getContentPane().add(jLabel1);

        accountNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(accountNoField);

        jLabel3.setText(" Ammount");
        getContentPane().add(jLabel3);

        dipositAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dipositAmountFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dipositAmountField);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        DepositButton.setText("Deposit");
        DepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DepositButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dipositAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dipositAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dipositAmountFieldActionPerformed

    private void accountNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNoFieldActionPerformed

    private void DepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositButtonActionPerformed
       StringBuilder error = new StringBuilder();
       int accountNo = 0;
       double depositAmount;
       if(accountNoField.getText().isEmpty()){
       error.append("Enter the ammount to deposit");
       }
       else {
           accountNo = Integer.parseInt(accountNoField.getText());
           depositAmount= Double.parseDouble(dipositAmountField.getText());
           int result = JOptionPane.showConfirmDialog(this, "Deposit"+depositAmount+"to account"+accountNo);
          
           
            if (result == JOptionPane.OK_OPTION) {
            try {
               System.out.println("getBalance");
                double balance = bank.getBalance(accountNo); 
                System.out.println(balance);
                balance= balance+depositAmount;
                System.out.println("new balance:"+balance);
                bank.updateBalance(accountNo,balance);
                
            } 
           catch (Exception e) {
               System.out.println(e);
            }
                    
        }
           
           if (error.length() > 0) {
            JOptionPane.showMessageDialog(this, error.toString(), "Deposit Warnings", JOptionPane.WARNING_MESSAGE);
        }
       this.dispose();
       }
          
    }//GEN-LAST:event_DepositButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DepositButton;
    private javax.swing.JTextField accountNoField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dipositAmountField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
