/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp.views;

import bankapp.accounts.Bank;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class WithdrawView extends javax.swing.JFrame {

    /**
     * Creates new form WithdrawMenu
     */
    private Bank bank;
    WithdrawView(Bank bank) {
       initComponents();
       setLocationRelativeTo(null);
        this.bank = bank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        accountNoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        withdrawAmountField = new javax.swing.JTextField();
        depositButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Withdraw Window");
        getContentPane().setLayout(new java.awt.GridLayout(3, 2, 2, 5));

        jLabel1.setText("  Account No :");
        getContentPane().add(jLabel1);

        accountNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(accountNoField);

        jLabel2.setText(" Amount :");
        getContentPane().add(jLabel2);
        getContentPane().add(withdrawAmountField);

        depositButton.setText("withdraw");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depositButton);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
       StringBuilder error = new StringBuilder();
       int accountNo = 0;
       double withdrawAmount;
       if(accountNoField.getText().isEmpty()){
       error.append("Enter the ammount to deposit");
       }
       else {
           accountNo = Integer.parseInt(accountNoField.getText());
           withdrawAmount= Double.parseDouble(withdrawAmountField.getText());
           try {
               System.out.println("getBalance");
            double balance = bank.getBalance(accountNo); 
            System.out.println(balance);
            if(withdrawAmount>balance){
                error.append("No sufficient Amount to Withdraw");
           }
            else{
                balance= balance-withdrawAmount;
                System.out.println("new balance:"+balance);
                bank.updateBalance(accountNo,balance);
                this.dispose();
           }
            
           } catch (Exception e) {
               System.out.println(e);
           }
           if (error.length() > 0) {
            JOptionPane.showMessageDialog(this, error.toString(), "Deposit Warnings", JOptionPane.WARNING_MESSAGE);
        }
       
       }
          
          
    }//GEN-LAST:event_depositButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void accountNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNoFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNoField;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField withdrawAmountField;
    // End of variables declaration//GEN-END:variables
}
